let stor = {
    weeklyScores : {
        1 : [],
        2 : [],
        3: [],
        4: [],
        5: [],
        6: [],
        7 : [],
        8: [],
        9: [],
        10: [],
        11: [],
        12: [],
        13: []
    },
  1: {
    'owner': 'Brady Fox',
    'ownerId': 1,
    'weeks': {
      1: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      2: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      3: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      4: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      5: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      6: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      7: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      8: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      9: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      10: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      11: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      12: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      13: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
    },
    'totalPointsFor': 0,
    'totalPointsAgainst': 0,
  },
  2: {
    'owner': 'David Wren',
    'ownerId': 2,
    'weeks': {
      1: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      2: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      3: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      4: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      5: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      6: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      7: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      8: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      9: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      10: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      11: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      12: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      13: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
    },
    'totalPointsFor': 0,
    'totalPointsAgainst': 0,
  },
  3: {
    'owner': 'Peter Geissinger',
    'ownerId': 3,
    'weeks': {
      1: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      2: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      3: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      4: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      5: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      6: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      7: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      8: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      9: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      10: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      11: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      12: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      13: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
    },
    'totalPointsFor': 0,
    'totalPointsAgainst': 0,
  },
  4: {
    'owner': 'Nathan Hart',
    'ownerId': 4,
    'weeks': {
      1: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      2: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      3: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      4: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      5: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      6: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      7: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      8: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      9: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      10: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      11: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      12: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      13: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
    },
    'totalPointsFor': 0,
    'totalPointsAgainst': 0,
  },
  5: {
    'owner': 'Michael Bernardino',
    'ownerId': 5,
    'weeks': {
      1: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      2: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      3: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      4: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      5: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      6: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      7: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      8: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      9: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      10: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      11: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      12: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      13: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
    },
    'totalPointsFor': 0,
    'totalPointsAgainst': 0,
  },
  6: {
    'owner': 'Jordan Sacks',
    'ownerId': 6,
    'weeks': {
      1: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      2: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      3: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      4: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      5: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      6: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      7: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      8: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      9: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      10: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      11: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      12: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      13: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
    },
    'totalPointsFor': 0,
    'totalPointsAgainst': 0,
  },
  7: {
    'owner': 'Jake Pearce',
    'ownerId': 7,
    'weeks': {
      1: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      2: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      3: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      4: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      5: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      6: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      7: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      8: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      9: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      10: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      11: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      12: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      13: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
    },
    'totalPointsFor': 0,
    'totalPointsAgainst': 0,
  },
  8: {
    'owner': 'Brad Phillips',
    'ownerId': 8,
    'weeks': {
      1: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      2: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      3: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      4: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      5: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      6: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      7: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      8: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      9: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      10: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      11: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      12: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      13: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
    },
    'totalPointsFor': 0,
    'totalPointsAgainst': 0,
  },
  9: {
    'owner': 'Kyle Dudzinski',
    'ownerId': 9,
    'weeks': {
      1: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      2: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      3: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      4: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      5: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      6: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      7: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      8: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      9: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      10: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      11: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      12: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      13: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
    },
    'totalPointsFor': 0,
    'totalPointsAgainst': 0,
  },
  10: {
    'owner': 'Jonathan Buerger',
    'ownerId': 10,
    'weeks': {
      1: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      2: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      3: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      4: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      5: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      6: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      7: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      8: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      9: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      10: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      11: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      12: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      13: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
    },
    'totalPointsFor': 0,
    'totalPointsAgainst': 0,
  },
  11: {
    'owner': 'Freddy Crawford',
    'ownerId': 11,
    'weeks': {
      1: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      2: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      3: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      4: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      5: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      6: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      7: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      8: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      9: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      10: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      11: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      12: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      13: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
    },
    'totalPointsFor': 0,
    'totalPointsAgainst': 0,
  },
  12: {
    'owner': 'Luke Papendick',
    'ownerId': 12,
    'weeks': {
      1: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      2: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      3: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      4: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      5: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      6: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      7: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      8: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      9: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      10: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      11: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      12: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
      13: {
        'kicker': 0,
        'pointsScored': 0,
        'wins': 0,
        'top6': 0,
      },
    },
    'totalPointsFor': 0,
    'totalPointsAgainst': 0,
  },
};

module.exports = stor;